# Generated by Django 4.1.13 on 2024-08-18 16:06

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=200)),
                (
                    "phone",
                    models.IntegerField(validators=[accounts.models.validate_length]),
                ),
                (
                    "password",
                    models.IntegerField(validators=[accounts.models.validate_length]),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("is_deleted", models.BooleanField(default=1)),
            ],
        ),
    ]
