# Generated by Django 4.1.13 on 2024-08-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("user_id", models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("income", "Income"), ("outcome", "Outcome")],
                        default="Income",
                        max_length=15,
                    ),
                ),
                ("transaction_date", models.DateField(default="1403-05-28")),
                ("transaction_time", models.TimeField(default="20:28:35")),
                ("user_id", models.IntegerField(blank=True)),
                ("description", models.TextField(blank=True, max_length=300)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="transactions.category",
                    ),
                ),
            ],
        ),
    ]
