# Generated by Django 4.1.13 on 2024-08-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="user_id",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_time",
            field=models.TimeField(default="20:53:17"),
        ),
    ]
