# Generated by Django 4.1.13 on 2024-08-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_category_user_id_alter_transactions_transaction_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="transaction_time",
            field=models.TimeField(default="20:53:41"),
        ),
    ]
