# Generated by Django 4.1.13 on 2024-08-21 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0004_alter_balance_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="transaction_date",
            field=models.DateField(default="1403-05-31"),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_time",
            field=models.TimeField(default="03:38:48"),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
