# Generated by Django 4.1.13 on 2024-08-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0005_alter_transactions_transaction_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="transaction_time",
            field=models.TimeField(default="03:41:13"),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="user_id",
            field=models.IntegerField(blank=True),
        ),
    ]
