# Generated by Django 5.1 on 2024-08-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0006_alter_transactions_transaction_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="transaction_date",
            field=models.DateField(default="1403-06-01"),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_time",
            field=models.TimeField(default="22:28:04"),
        ),
    ]
