# Generated by Django 5.1 on 2024-08-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_alter_transactions_transaction_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="transaction_time",
            field=models.TimeField(default="22:39:55"),
        ),
    ]
